- name: Restart HTTPD
  service: name='{{ redhat_apache }}' state=restarted

- name: Restart apache2
  service: name='{{ debian_apache }}' state=restarted

- name: Install telnet
  yum: pkg=telnet state=latest

