- hosts: webserver
  pre_tasks:
    - name: When did role start
      command: date
      register: _time

    - debug: var=_time.stdout_lines[0]

  roles:
    - webservers

  post_tasks:
      - name: When did role end
        command: date
        register: _time

      - debug: var=_time.stdout_lines[0]