Vagrant.configure(2) do |config|
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.define "ansible" do |ansible|

    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.name = "ansible-server"

    end
    ansible.vm.synced_folder "../", "/ansible_code", type: 'nfs'
#    ansible.vm.synced_folder "../ansibleserver", "/ansible_ansibleserver", type: 'nfs'
    ansible.vm.box = "ubuntu/trusty64"
    ansible.vm.hostname = "controller.mylab.com"
    ansible.vm.network :private_network, ip: "10.0.0.10"
    ansible.hostmanager.aliases = %w(controller)

    ansible.vm.provision "shell", inline: <<-SHELL

    sudo apt-get update
    sudo apt-get upgrade
    sudo apt-get dist-upgrade
    sudo apt-get install software-properties-common
    sudo apt-add-repository ppa:ansible/ansible
    sudo apt-get update
    sudo apt-get install build-essential libssl-dev libffi-dev python-dev python-pip -y
    sudo apt-get install ansible -y
    sudo pip install --upgrade setuptools
    sudo pip install cryptography
    sudo pip install --upgrade ansible
    sudo cp /ansible_code/hosts /etc/ansible/hosts
    sudo cp /vagrant/id_rsa /root/.ssh/
    sudo cp /vagrant/id_rsa.pub /root/.ssh/
    sudo cp /vagrant/sshd_config /etc/ssh/sshd_config
    sudo service ssh restart
    sudo chmod 400 /root/.ssh/id_rsa*
    SHELL

  end

  config.vm.define "app1" do |app1|
    config.vm.provider "virtualbox" do |v|
      v.name = "ansible-app1"
    end
    app1.vm.box = "ubuntu/trusty64"
    app1.vm.hostname = "app1.mylab.com"
    app1.vm.network :private_network, ip: "10.0.0.11"
    app1.hostmanager.aliases = %w(app1)
    app1.vm.provision "shell", inline: <<-SHELL
    sudo cp /vagrant/sshd_config /etc/ssh/sshd_config
    sudo service ssh restart
    SHELL
  end

  config.vm.define "db1" do |db1|
    config.vm.provider "virtualbox" do |v|
      v.name = "ansible-db1"
    end
    db1.vm.box = "ubuntu/trusty64"
    db1.vm.hostname = "db1.mylab.com"
    db1.vm.network :private_network, ip: "10.0.0.12"
    db1.hostmanager.aliases = %w(db1)
    db1.vm.provision "shell", inline: <<-SHELL
    sudo cp /vagrant/sshd_config /etc/ssh/sshd_config
    sudo service ssh restart
    SHELL

  end
end
