- name: Install Apache Webserver on RedHat
  yum: pkg='{{ redhat_apache }}' state=latest
  notify:
     - Restart HTTPD
     - Install telnet
  when: ansible_os_family == 'RedHat'

- name: Install apache2 webserver on Debian
  apt: pkg='{{ debian_apache }}' state=latest
  notify: Restart apache2
  when: ansible_os_family == 'Debian'

